---
- include_tasks: nbdkit.yml
  when: os_migrate_nbkit|default(false)|bool  
- include_tasks: virt_v2v.yml
  when: os_migrate_virt_v2v|default(true)|bool  
- include_tasks: create_network_port.yml
  when: os_migrate_create_network_port|default(true)|bool
- include_tasks: create_os_instance.yml
  when: os_migrate_create_os_instance|default(true)|bool
- include_tasks: teardown.yml
  when: os_migrate_tear_down|default(false)|bool
