---
- name: Find vddk-libdir
  ansible.builtin.shell: |
    find / -name vmware-vix-disklib 2>/dev/null | xargs dirname
  register: vddk_libdir

- name: Dump passwd file
  ansible.builtin.shell: |
    echo "{{ vcenter_password }}" > /tmp/passwd

- name: Make sure virtqemud is started
  ansible.builtin.service:
    name: virtqemud-ro.socket
    state: started

- name: Import VMware volume to Openstack
  environment:
    OS_CLOUD: "{{ dst_cloud }}"
  os_migrate.vmware_migration_kit.import_vmware_volume:
    vcenter_username: "{{ vcenter_username }}"
    vcenter_hostname: "{{ vcenter_hostname }}"
    esxi_hostname: "{{ esxi_hostname }}"
    vddk_libdir: "{{ vddk_libdir }}"
    vddk_thumbprint: "{{ vddk_thumbprint }}"
    conversion_host_id: "{{ conversion_host_id }}"
    vm_name: "{{ vm_name }}"
