import_workloads_use_socks: "{{ use_socks | default(true) | bool }}"
import_workloads_cbt_sync: "{{ cbt_sync | default(false) | bool }}"
import_workloads_cutover: "{{ cutover | default(false) | bool }}"
import_workloads_converted: "{{ converted | default(false) | bool }}"
import_workloads_os_migrate_virt_v2v: "{{ os_migrate_virt_v2v | default(false) | bool }}"
import_workloads_os_migrate_nbdkit: "{{ os_migrate_nbdkit | default(true) | bool }}"
import_workloads_debug: "{{ debug | default(false) | bool }}"
import_workloads_local_disk_path: "{{ local_disk_path | default(omit) }}"
import_workloads_libdir: "{{ libdir | default('/usr/lib/vmware-vix-disklib') }}"
# Teardown for testing only or dry runs:
import_workloads_os_migrate_tear_down: "{{ os_migrate_tear_down | default(false) | bool }}"

# UUID of the conversion host instance
import_workloads_instance_uuid: ""

import_workloads_used_mapped_networks: "{{ used_mapped_networks | default(false) | bool }}"
import_workloads_image_metadata:
  - hw_rng_model='virtio'
  - os_type='linux'
  - hw_vif_model='virtio'
  - hw_scsi_model='virtio-scsi'
  - hw_qemu_guest_agent='True'
  - hw_disk_bus='scsi'
  - os_distro='rhel'
  - hw_machine_type='q35'
  - hw_firmware_type='uefi'
  - hw_boot_mode='uefi'
  - cinder_img_volume_type='rhcs6-gp3'

import_workloads_boot_from_cinder: "{{ boot_from_cinder | default(false) | bool }}"
