---
galaxy_info:
  author: Mathieu Bultel <mat.bultel@gmail.com>
  description: Exports VMware virtual machine metadata from vSphere.
  license: Apache-2.0

  min_ansible_version: "2.12" # Adjust as needed

  galaxy_tags:
    - vmware
    - vsphere
    - openstack
    - migration
    - metadata
    - export
    - discovery
    - automation

dependencies: []
