---
- name: Create instance ports for mapped networks
  when: import_workloads_used_mapped_networks
  block:
    - name: Create network ports
      os_migrate.vmware_migration_kit.create_network_port:
        cloud: "{{ dst_cloud }}"
        os_migrate_nics_file_path: "{{ os_migrate_vmw_data_dir }}/{{ vm_name }}/nics.json"
        vm_name: "{{ vm_name }}"
        used_mapped_networks: true
        security_groups: ["{{ security_groups | default('default') }}"]
        use_fixed_ips: "{{ import_workloads_use_fixed_ips | default(false) | bool }}"
      register: ports_uuid
      when: import_workloads_used_mapped_networks|default(true)|bool

    - name: Extract port info
      ansible.builtin.set_fact:
        nics: "{{ ports_uuid.ports | default([]) }}"
      when: os_migrate_create_network_port|default(true)|bool

- name: Create instance ports for non mapped networks
  when: not import_workloads_used_mapped_networks
  block:
    - name: Create network port
      os_migrate.vmware_migration_kit.create_network_port:
        cloud: "{{ dst_cloud }}"
        os_migrate_nics_file_path: "{{ os_migrate_vmw_data_dir }}/{{ vm_name }}/macs.json"
        vm_name: "{{ vm_name }}"
        used_mapped_networks: false
        security_groups: ["{{ security_groups | default('default') }}"]
        network_name: "{{ openstack_private_network }}"
      register: ports_uuid
      when: not import_workloads_used_mapped_networks|default(true)|bool

    - name: Extract port info
      ansible.builtin.set_fact:
        nics: "{{ ports_uuid.ports | default([]) }}"
      when: os_migrate_create_network_port|default(true)|bool
