---
galaxy_info:
  author: Mathieu Bultel <mat.bultel@gmail.com>
  description: Converts VMware VM metadata into a format suitable for OpenStack resource creation.
  license: Apache-2.0

  min_ansible_version: "2.12"

  galaxy_tags:
    - vmware
    - openstack
    - migration
    - metadata
    - transformation
    - automation

dependencies: []
